#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -eu


# -- Environment variables.

export QT_QUICK_CONTROLS_STYLE=org.kde.breeze


# -- Identify the command being blocked (apt, apt-get, dpkg, etc.).

CMD=$(basename "$0")


# -- Identify the actual user (even if sudo was used).

REAL_USER="${SUDO_USER:-$USER}"


# -- Use a log.

LOGDIR=/var/log/nitrux
LOGFILE="$LOGDIR/hcel-software.log"

if [ -w "/var/log" ]; then
    mkdir -p "$LOGDIR" 2>/dev/null || true
    printf '%s BLOCKED: %s USER: %s\n' "$(date -Iseconds)" "$CMD" "$REAL_USER" >>"$LOGFILE" 2>/dev/null || true
fi


# -- Notify users that there is no system package manager and make them understand this is intentional.

dist=$(grep -oP 'PRETTY_NAME=\K.*' /etc/os-release | tr -d '"')
software_management_url='https://nxos.org/tutorial/software-management/'
vendor='Nitrux Latinoamericana S.C.'
fecha=$(date +%Y)

BOLD='\e[1m'
UNDERLINE='\e[4m'
NF='\e[0m'

WHITE='\033[1;37m'
YELLOW='\033[1;33m'
NC='\033[0m'

TITLE="Command Blocked: $CMD"

MSG="<b>Usage of <tt>$CMD</tt> is not supported on the host system.</b><br><br>"
MSG+="Nitrux focuses on user-centric, rootless software management. On Nitrux, the preferred ways to install new software are:<br><br>"
MSG+="&nbsp;&bull;&nbsp;<b>AppBoxes</b> (GUI apps, CLI tools, utilities, some WMs)<br>"
MSG+="&nbsp;&bull;&nbsp;<b>Flatpak</b> (additional GUI applications)<br>"
MSG+="&nbsp;&bull;&nbsp;<b>Distrobox</b> (tasks requiring a package manager, such as compiling or workflow transition)<br><br>"
MSG+="For details, see the documentation:<br><br>"
MSG+="<b>Software Management: $software_management_url</b><br><br>"
MSG+="<hr><b>The command was not executed.</b>"

if [ "$EUID" -ne 0 ] && [ -n "${DISPLAY-}" ] && command -v kdialog >/dev/null 2>&1; then
    kdialog --title "$TITLE" --msgbox "$MSG" --geometry 600x400
else
    echo ' '
    echo '                          =                  '
    echo '                          =     .            '
    echo '                          =     .:::         '
    echo '::+.      ....:......     =         :::      '
    echo '%+-#=  ..:    :-:    .    =            :::.  '
    echo '--#-=-- --    .:#---.     =            .=#%#='
    echo '- .**=#= :      *    .    =         :+#%%%#=.'
    echo '-   -# =#.    --     .    =      :+%%%%*-.   '
    echo '        ..  ..  ....      =   -+%%%%*-       '
    echo '                          =-*%%%%+:          '
    echo '                          +%%#+:             '
    echo ' '
    echo ' '
    echo -e "$dist"
    echo ' '
    echo -e "(c) $fecha Some Rights Reserved. Made by $vendor"
    echo ' '
    echo ' '
    echo -e "${YELLOW}#####################################################${NC}"
    echo -e "${YELLOW}# Usage of $CMD is not supported on the host system. #${NC}"
    echo -e "${YELLOW}#####################################################${NC}"
    echo ' '
    echo -e "Nitrux focuses on user-centric, rootless software management."
    echo ' '
    echo -e "Use ${BOLD}AppBoxes${NF}, ${BOLD}Flatpak${NF}, or ${BOLD}Distrobox${NF} for tasks requiring a package manager, such as compiling or workflow transition."
    echo ' '
    echo -e "For details, see the documentation:"
    echo -e "  ${WHITE}${UNDERLINE}$software_management_url${NC}${NF}"
    echo ' '
fi

exit 1
