#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -eu


# -- Environment variables.

export QT_QUICK_CONTROLS_STYLE=org.kde.breeze


# -- Notify users that running the distribution on a VM or low-spec hardware is *NOT THE INTENDED USE CASE*.

IS_VM=0

if [ -r /sys/class/dmi/id/product_name ]; then
    PRODUCT_NAME=$(cat /sys/class/dmi/id/product_name)
    if echo "$PRODUCT_NAME" | grep -qiE "VirtualBox|VMware|KVM|Bochs|QEMU|Standard PC|Virtual Machine"; then
        IS_VM=1
    fi
fi

if grep -q "hypervisor" /proc/cpuinfo; then
    IS_VM=1
fi

if [ "$IS_VM" -eq 0 ]; then
    TOTAL_RAM_MB=$(grep MemTotal /proc/meminfo | awk '{print $2 / 1024}')
    PHYSICAL_CORES=$(lscpu | grep "^Core(s) per socket:" | awk '{print $4}')
    THREADS=$(lscpu | grep "^CPU(s):" | awk '{print $2}')

    if (( $(echo "$TOTAL_RAM_MB < 4096" | bc -l) )) || (( PHYSICAL_CORES < 4 )) || (( THREADS < 4 )); then
        notify-send \
            -a "System Message" \
            -u critical \
            --action=Understood \
            -i "dialog-warning" \
            "System Specs Warning" \
            "This system has less than 4GB of RAM, 4 physical cores, or 4 threads. Performance will be limited. Nitrux does not target low-spec hardware."
    fi

    exit 0
fi

sleep 5

notify-send \
    --app-name="System Message" \
    --urgency=critical \
    --icon="dialog-warning" \
    --wait \
    --action="Understood=Understood" \
    "VM Detected" \
    "Nitrux is running in a Virtual Machine; performance and experience will be severely limited.\n\nDismiss this notification to view the virtualization policy."

TITLE="Virtualizing Nitrux"

MSG="We have discontinued integration and support features intended for running Nitrux as a guest OS. While Nitrux will continue to run in most hypervisors, components such as SPICE integration, the QXL X.Org driver, and the Hyper-V modules, daemons, and OpenRC services are no longer included.<br><br>"
MSG+="Despite our previous efforts to provide guidance, we repeatedly encountered users applying incorrect configurations, further limiting performance in already-constrained virtualized environments, among other issues stemming from hypervisor quirks.<br><br>"
MSG+="<b>We never intended Virtual Machines to be the platform for using Nitrux.</b><br><br>"
MSG+="Nitrux is tuned and optimized for physical systems, where users can experience its design, performance, and intent as we built it.<br><br>"
MSG+="Please review the documentation:<br><br>"
MSG+="<b>System Requirements: https://nxos.org/tutorial/how-to-install-nitrux/#system-requirements/</b><br><br>"
MSG+="<font color='orange'><b>⚠️ Important:</b></font> Bug reports regarding running Nitrux as a guest VM will be closed.<br><br>"
MSG+="<hr><b>The system will now reboot.</b>"

kdialog --title "$TITLE" --msgbox "$MSG" --geometry 600x400

loginctl reboot || hyprctl dispatch exit
