#!/usr/bin/env sh

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Force NetworkManager to ignore DHCP DNS for all connections preventing ISP leaks into the local dnsmasq instance.

INTERFACE="$1"
STATUS="$2"

if [ "$STATUS" = "up" ]; then
    UUID=$(nmcli -g GENERAL.CONNECTION state show "$INTERFACE")

    # -- Check if ignore-auto-dns is already set to 'yes'.

    CURRENT_V4=$(nmcli -g ipv4.ignore-auto-dns connection show "$UUID")
    CURRENT_V6=$(nmcli -g ipv6.ignore-auto-dns connection show "$UUID")

    if [ "$CURRENT_V4" != "yes" ] || [ "$CURRENT_V6" != "yes" ]; then
        logger -t nm-dns-enforce "Enforcing ignore-auto-dns for connection $UUID on $INTERFACE"
        
        # -- Enable ignore-auto-dns and CLEAR per-connection DNS servers.

        nmcli connection modify "$UUID" \
            ipv4.ignore-auto-dns yes \
            ipv6.ignore-auto-dns yes \
            ipv4.dns "" \
            ipv6.dns ""
        
        # -- Re-apply the connection to ensure changes take effect immediately.

        nmcli connection up "$UUID" &
    fi
fi
