#!/bin/sh
set -eu

root_uuid="$(grub-probe --target=fs_uuid / 2>/dev/null || true)"
[ -n "$root_uuid" ] || exit 0

printf '%s\n' "submenu 'Nitrux [Intel Xe mode]' {"

find /boot -maxdepth 1 -type f -name 'vmlinuz-*' 2>/dev/null |
sort -rV |
while IFS= read -r k; do
    ver="${k#/boot/vmlinuz-}"
    i="/boot/initrd.img-$ver"

    [ -e "$i" ] || continue

    printf '%s\n' "  menuentry 'Nitrux [Intel Xe mode] ($ver)' {"
    printf '%s\n' "    search --no-floppy --fs-uuid --set=root $root_uuid"
    printf '%s\n' "    linux $k amd_prefcore=enabled amd_pstate=active amdgpu.cik_support=1 amdgpu.ppfeaturemask=0xffffffff amdgpu.si_support=1 amdgpu.vm_update_mode=3 apparmor=1 audit=0 clocksource=tsc fsck.mode=skip hardened_usercopy=1 hpet=disable i915.force_probe=!* init_on_free=1 intel_iommu=on intel_pstate=enable kfence=off libahci.ignore_sss=1 lsm=capability,yama,bpf,apparmor,landlock modprobe.blacklist=iTCO_wdt,sp5100_tco nohz=on nosgx nvidia_drm.modeset=1 nvme_core.default_ps_max_latency_us=0 nvme_core.multipath=Y overlayroot=tmpfs:swap=1,recurse=0 page_alloc.shuffle=1 pti=on quiet radeon.cik_support=0 radeon.si_support=0 randomize_kstack_offset=1 rcu_nocbs=all rcupdate.rcu_expedited=1 rcutree.enable_rcu_lazy=1 root=UUID=$root_uuid slab_nomerge splash tsc=nowatchdog tsc=reliable usbcore.autosuspend=-1 vdso32=0 vsyscall=none xe.force_probe=* xhci_hcd.quirks=270336 zswap.compressor=zstd zswap.enabled=1 zswap.max_pool_percent=20 zswap.zpool=zsmalloc"
    printf '%s\n' "    initrd $i"
    printf '%s\n' "  }"
done

printf '%s\n' "}"
