# Default values for dmemcg-booster in Nitrux
# Nitrux Performance & Security Tuning
# 2026 (c) Nitrux Latinoamericana S.C.

# Flatpak Steam-oriented allow rules
allow_app=com.valvesoftware.Steam
allow_class=steam,steam_app,gamescope
# allow_title=

# Optional for Proton stack
allow_exe=pressure-vessel,wine,gamescope,steamwebhelper
