# Enables Page Attribute Table for improved performance and preserves video memory allocations across suspend/resume cycles.
options nvidia NVreg_UsePageAttributeTable=1
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp

# Forces the NVIDIA driver to use software-based I²C (bit-banged I²C) instead of the GPU’s hardware I²C controller.
options nvidia NVreg_RegistryDwords=RMUseSwI2c=0x01;RMI2cSpeed=100
